ListaDeTarefas/gerenciador_de_tarefas/app/urls.py
from django.urls import path
from .views.tarefa_views import *
from .views.usuario_views import *
from .views import *

# gerencia as rotas da aplicacao
urlpatterns = [
    path('listar_tarefas/', listar_tarefas, name='listar_tarefas'),
    path('cadastrar_tarefa/', cadastrar_tarefa, name='cadastrar_tarefa'),
    path('editar_tarefa/<int:id>', editar_tarefa, name='editar_tarefa'),
    path('remover_tarefa/<int:id>', remover_tarefa, name='remover_tarefa'),
    # entre <> passamos o tipo do parametro e o parametro, deve ser o mesmo nome no metodo editar_tarefa na view

    path('cadastrar_usuario/', cadastrar_usuario, name='cadastrar_usuario'),
    path('logar_usuario/', logar_usuario, name='logar_usuario'),
    path('deslogar_usuario/', deslogar_usuario, name='deslogar_usuario'),
]

ListaDeTarefas/gerenciador_de_tarefas/gerenciador_de_tarefas/urls.py
from django.contrib import admin
from django.urls import path, include

# gerencia as rotas do projeto
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

ListaDeTarefas/gerenciador_de_tarefas/app/models.py
from django.contrib.auth.models import User
from django.db import models


class Tarefa(models.Model):
    PRIORIDADE_CHOICES = [
        ("A", "Alta"),
        ("N", "Normal"),
        ("B", "Baixa"),
    ]

    tituloo = models.CharField(max_length=30, null=False, blank=False)
    descricao = models.CharField(max_length=100, null=False, blank=False)
    data_expiracao = models.DateField(null=False, blank=False)
    prioridade = models.CharField(max_length=1, choices=PRIORIDADE_CHOICES, null=False, blank=False)
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

# uma tarefa pode pertencer a apenas 1 usuario, mas um usuario pode ter varias tarefas

ListaDeTarefas/gerenciador_de_tarefas/app/views/tarefa_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from ..forms import TarefaForm
from ..entidades.tarefa import Tarefa
from ..services import tarefa_service
# renderizar template


@login_required()
def listar_tarefas(request):
    tarefas = tarefa_service.listar_tarefas(request.user)
    # capturando todas as tarefas
    return render(request, 'tarefas/listar_tarefas.html', {"tarefas": tarefas})


@login_required()
def cadastrar_tarefa(request):
    if request.method == "POST":
        form_tarefa = TarefaForm(request.POST)
        if form_tarefa.is_valid():
           tituloo = form_tarefa.cleaned_data["tituloo"]
           descricao = form_tarefa.cleaned_data["descricao"]
           data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
           prioridade = form_tarefa.cleaned_data["prioridade"]
           tarefa_nova = Tarefa(tituloo=tituloo,
                                 descricao=descricao,
                                 data_expiracao=data_expiracao,
                                 prioridade=prioridade,
                                 usuario=request.user)
           tarefa_service.cadastrar_tarefa(tarefa_nova)
           return redirect('listar_tarefas')
    else:
        form_tarefa = TarefaForm()
    return render(request, 'tarefas/form_tarefa.html', {"form_tarefa": form_tarefa})


@login_required()
def editar_tarefa(request, id):
    # buscar qual tarefa quero editar no bd
    tarefa_bd = tarefa_service.listar_tarefa_id(id)

    if tarefa_bd.usuario != request.user:
        return HttpResponse("Não permitido")

    # criamos o form com base nas informacoes que vieram do banco de dados
    form_tarefa = TarefaForm(request.POST or None, instance=tarefa_bd)
    # quando alterarmos as infos e clicar em 'salvar' verificamos se as mesmas sao validas
    if form_tarefa.is_valid():
        # captura de todas as informacoes do form
        tituloo = form_tarefa.cleaned_data["tituloo"]
        descricao = form_tarefa.cleaned_data["descricao"]
        data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
        prioridade = form_tarefa.cleaned_data["prioridade"]
        # criamos um novo objeto do tipo Tarefa com as novas infos
        tarefa_nova = Tarefa(tituloo=tituloo,
                             descricao=descricao,
                             data_expiracao=data_expiracao,
                             prioridade=prioridade,
                             usuario=request.user)
        # Enviamos tanto a tarefa antiga(bd) quanto a tarefa nova pro metod editar_tarefa
        tarefa_service.editar_tarefa(tarefa_bd, tarefa_nova)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/form_tarefa.html', {"form_tarefa": form_tarefa})


@login_required()
def remover_tarefa(request, id):
    # retorna o id da tarefa a ser removida
    tarefa_bd = tarefa_service.listar_tarefa_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse("Não permitido")
    if request.method == "POST":
        tarefa_service.remover_tarefa(tarefa_bd)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/confirma_exclusao.html', {'tarefa': tarefa_bd})

ListaDeTarefas/gerenciador_de_tarefas/app/templates/tarefas/confirma_exclusao.html
{% extends 'base.html' %}

{% block conteudo%}

<div class="card mb-3 w-50 mt-5" style="margin: 0 auto;">
    <div class="card-header bg-warning text-dark font-weight-bold">
        Tem certeza que deseja excluir a tarefa abaixo?
    </div>
    <div class="card-body bg-dark">
        <h5 class="card-title text-warning">
            {{ tarefa.tituloo }}
        </h5>
        <p class="card-text lead text-warning">
            {{ tarefa.descricao}}
        </p>
        <hr class="border-warning">
        <form method="POST">
            {% csrf_token%}
            <button class="btn btn-danger btn-block">Remover</button>
            <a class="btn btn-primary btn-block" href="{% url 'listar_tarefas' %}">Cancelar</a>
        </form>
    </div>
</div>

{% endblock conteudo %}

ListaDeTarefas/gerenciador_de_tarefas/app/templates/tarefas/form_tarefa.html
{% extends 'base.html '%}
{% load meus_filtros %}

{% block conteudo %}

<h3>Cadastrar tarefa</h3>

<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        {{ form_tarefa.tituloo.errors }}
        <label>Titulo: </label>
        {{ form_tarefa.tituloo|addclass:'form-control w-50'}}
    </div>
    <div class="form-group">
        {{ form_tarefa.descricao.errors }}
        <label>Descrição: </label>
        {{ form_tarefa.descricao|addclass:'form-control w-50'}}
    </div>
    <div class="form-group">
        {{ form_tarefa.data_expiracao.errors }}
        <label>Data de Expiração: </label>
        {{ form_tarefa.data_expiracao|addclass:'form-control w-50'}}
    </div>
    <div class="form-group">
        {{ form_tarefa.prioridade.errors }}
        <label>Prioridade: </label>
        {{ form_tarefa.prioridade|addclass:'form-control w-50'}}
    </div>
    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-primary">
    </div>
</form>

{% endblock conteudo%}

ListaDeTarefas/gerenciador_de_tarefas/app/templates/tarefas/listar_tarefas.html
{% extends 'base.html '%}
{% block conteudo %}

{% if tarefas.count == 0 %}

<div class="jumbotron container bg-dark text-center">
    <h3 class="text-warning">Você ainda não possui tarefas.</h3>
    <p class="lead text-white">Clique no botão abaixo para cadastrar sua primeira tarefa.</p>
    <hr class="my-4 border-warning">
    <a class="btn btn-warning btn-lg" href="{% url 'cadastrar_tarefa' %}" role="button">Cadastrar</a>
</div>

{% else %}

<h1>Tarefas de {{ user.username}}</h1>
{% for tarefa in tarefas %}
<div class="card mb-3 w-75">
    <div class="card-header bg-warning text-dark font-weight-bold">
        <span>Prioridade: {{ tarefa.get_prioridade_display }}</span>
    </div>
    <div class="card-body bg-dark">
        <h5 class="card-title text-warning">
            {{ tarefa.tituloo }}
        </h5>
        <p class="card-text lead text-warning">
            {{ tarefa.descricao}}
        </p>
        <hr class="border-warning">
        <a href="{% url 'editar_tarefa' tarefa.id %}"
           class="btn btn-warning w-25" title="Editar tarefa nº {{ tarefa.id }}">
            <i class="fas fa-edit fa-2x text-light"></i></a>
        <a href="{% url 'remover_tarefa' tarefa.id %}"
           class="btn btn-danger w-25" title="Exlcuir tarefa nº {{ tarefa.id }}">
            <i class="fas fa-trash-alt fa-2x"></i></a>
    </div>
</div>
{%endfor%}

<a href="{% url 'cadastrar_tarefa' %}" class="btn btn-primary">
    Cadastrar Tarefa</a>
{% endif %}

{% endblock conteudo %}